# Generated by Django 3.1.2 on 2020-10-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Numbering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=3, verbose_name='Код')),
                ('fr', models.CharField(max_length=7, verbose_name='От')),
                ('to', models.CharField(max_length=7, verbose_name='До')),
                ('capacity', models.IntegerField(verbose_name='Емкость')),
                ('operator', models.CharField(max_length=100, verbose_name='Оператор')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
            ],
        ),
    ]
