# Generated by Django 3.1.2 on 2020-10-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbering',
            name='fr',
            field=models.IntegerField(verbose_name='От'),
        ),
        migrations.AlterField(
            model_name='numbering',
            name='to',
            field=models.IntegerField(verbose_name='До'),
        ),
    ]
